### ISSUE TITLE
Checkbox boolean values

### ISSUE THREAD

**Issue by lolsborn** [gorilla/schema#1]
I have the following struct

```
type DeviceProfile struct {
    Title        string `json:"title"`
    Model        string `json:"model"`
    Mfr          string `json:"mfr"`
    Ssl          bool   `json:"ssl"`
}
```

And a checkbox in my html form:

```
<input type="checkbox" name="Ssl">
```

When I decode the form DeviceProfile.Ssl is always false because the HTML value for a checked checkbox is the string "on".

It seems like it would be helpful to accept "on" as a valid boolean true value.  Note that if the checkbox is not checked the returned value is empty.

**Comment by esantoro** [comment]
I had a similar problem and solved it this way:

    type Model struct {
       MyField    bool   `schema:"my_field" sql:"default: false"`
    }

In my html:

    <div class="form-group">
    <label>
        MyField <input type="checkbox" name="my_field"/>
    </label>
  </div>


With the sql type defaulting to false, the decoding works correctly, assuming the semantic of the checkbutton (from a user perspective) is that "checking the checkbox means true and leaving it unchecked means false"

**Comment by joegalaxy71** [comment]
Thanks esantoro, This works perfectly in my case.

**Comment by esantoro** [comment]
You're welcome :)
