### ISSUE TITLE
Need to document `[]` requirement in struct annotations for array fields

### ISSUE THREAD

**Issue by BourgeoisBear** [gorilla/schema#102]
With this struct annotation, Decode() silently fails to decode the array:

```go
type MyStruct struct {
   MyArray []uint32 `schema:"myArray"`
}
```

With this struct annotation, Decode() succeeds:

```go
type MyStruct struct {
   MyArray []uint32 `schema:"myArray[]"`
}
```

Any objections to adding this to the documentation?

**Comment by wemgl** [comment]
I'm having an issue with at right now @BourgeoisBear. Your post pointed me in the right direction about how to tag my struct's array field, but I haven't figured out how to do the markup. I want to created a multiple select but I haven't been able to get "myArray[]" as the name of the select field, or the options, to properly decode. Any ideas? Also, yeah, documentation on this would be amazing.

**Comment by BourgeoisBear** [comment]
@wemgl I'm just using a jQuery `$.post()` call to it, so on the golang side:

```go
type MyStruct struct {
   TheItems     []uint32    `schema:"items[]"`
}
```

and for the post in javascript:

```javascript
$.post('/path/to/action', { items: [1, 2, 3, 4] }, function(jsonRet) {
   // DO STUFF
}, 'json');
```

**Comment by wemgl** [comment]
Thanks for the quick reply @BourgeoisBear. You're right. I was able to solve my problem by removing the `[]` from the HTML element name, removing the `[]` from the struct field's tag, and POST-ing the form. Everything worked after that.
