### ISSUE TITLE
Empty string element in a slice disappears after decoding

### ISSUE THREAD

**Issue by mariaefi29** [gorilla/schema#105]
For example, I have a struct:

`type Post struct {
	Images        []string     
}
`

If I want to put in the struct values like (contains **three** elements, **including** empty string):

`["a", "", "b"]`

After decoding I have a slice with **two** elements **excluding** an empty string as a result.

Could you please tell me if it Is a bug or a way it works? Thank you!

**Comment by kisielk** [comment]
Can you please provide a full code sample to reproduce this?

**Comment by mariaefi29** [comment]
`package main

import (
	"fmt"
	"github.com/gorilla/schema"
	"net/url"
)

func main() {

	type Images struct {
		Images []string
	}

	decoder := schema.NewDecoder()

	values := url.Values{}
	values.Add("Images", "a")
	values.Add("Images", "")
	values.Add("Images", "b")

	images := Images{}

	fmt.Println("Values are --->", values)
	fmt.Println("The length of values is --->", len(values["Images"]))

	err := decoder.Decode(&images, values)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("Images after decoding are --->", images)
	fmt.Println("The length of Images after decoding is --->", len(images.Images))

}`

**Comment by mariaefi29** [comment]
```
package main

import (
	"fmt"
	"github.com/gorilla/schema"
	"net/url"
)

func main() {

	type Images struct {
		Images []string
	}

	decoder := schema.NewDecoder()

	values := url.Values{}
	values.Add("Images", "a")
	values.Add("Images", "")
	values.Add("Images", "b")

	images := Images{}

	fmt.Println("Values are --->", values)
	fmt.Println("The length of values is --->", len(values["Images"]))

	err := decoder.Decode(&images, values)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("Images after decoding are --->", images)
	fmt.Println("The length of Images after decoding is --->", len(images.Images))

}
```

**Comment by kisielk** [comment]
Hi @mariaefi29 

Sorry for taking a while back to you. What you need to do is call `decoder.ZeroEmpty(true)` before calling the `Decode` method. That will cause empty strings to produce the zero value of the decoded type, otherwise they are ignored.

**Comment by mariaefi29** [comment]
Thank you very much for your help!

**Comment by novikov1337danil** [comment]
> Hi @mariaefi29
> 
> Sorry for taking a while back to you. What you need to do is call `decoder.ZeroEmpty(true)` before calling the `Decode` method. That will cause empty strings to produce the zero value of the decoded type, otherwise they are ignored.

Hello! For me ZeroEmpty still not working. I still get an empty string instead of nil

**Comment by elithrar** [comment]
The zero value in Go for a string is “”. You may want [][]byte instead, if
dealing with image data.
