### ISSUE TITLE
encoder does not round trip structs containing struct fields

### ISSUE THREAD

**Issue by lrewega-stripe** [gorilla/schema#118]
Given a set of values,
```
var raw = map[string][]string{
	"Inner.A": []string{"1"},
	"Inner.B": []string{"2"},
	"C":       []string{"3"},
}
```
we can decode correctly into the following type `Bar`:
```
type Foo struct {
	A int
	B int
}

type Bar struct {
	Inner Foo
	C     int
}
```

However, encoding `Bar` results in a different map:
```
map[string][]string{
	"A":       []string{"1"},
	"B":       []string{"2"},
	"C":       []string{"3"},
}
```

This behaviour is surprising! I should be able to encode & decode a type and have the results match the input.

I can use different tags for encoding to get around this (e.g. `schema:"Inner.A"`) but it gets tedious (implementation details leak circularly).

[Play Link](https://play.golang.org/p/Kz4Mw9GlVpw)

**Comment by shutej** [comment]
I just discovered this today. This is very unintuitive behavior and prevents my use case!!!

**Comment by kisielk** [comment]
I would say this is definitely a bug and not intentional behaviour. I am quite busy these days so I'm not sure when I will have time to look into it. If you don't mind doing some further investigation it would be much appreciated.
