### ISSUE TITLE
Decode form data based on schema

### ISSUE THREAD

**Issue by shivarammysore** [gorilla/schema#124]
**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is -

Assume a schema (`schema.json`)

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "A registration form",
  "description": "A simple form example.",
  "type": "object",
  "required": [
    "firstName",
    "lastName"
  ],
  "properties": {
    "firstName": {
      "type": "string",
      "title": "First name",
      "default": "Chuck"
    },
    "lastName": {
      "type": "string",
      "title": "Last name"
    },
    "age": {
      "type": "integer",
      "title": "Age"
    },
    "bio": {
      "type": "string",
      "title": "Bio"
    },
    "password": {
      "type": "string",
      "title": "Password",
      "minLength": 3
    },
    "telephone": {
      "type": "string",
      "title": "Telephone",
      "minLength": 10
    }
  }
}
```
One can generate various forms for WebUI based on this schema from various JSON forms based generation utilities.

I would like to handle POST request from such a web form using `gorilla/schema`

```
import (
  "github.com/lestrrat-go/jsschema"
  "github.com/lestrrat-go/jsschema/validator"
)

func JSONFormHandler(w http.ResponseWriter, r *http.Request) {
	err := r.ParseForm()
	if err != nil {
		// Handle error
	}
	decoder := schema.NewDecoder()
        s := schema.ReadFile("schema.json")
        // validate the schema
        v := validator.New(s)

        // Ideally, I would like to store the parsed form in an "Object" that I can validate against schema
        Object  = decoder.Decode(r.PostForm)
      // more work here to get this done ...

         w.WriteHeader(http.StatusOK)
}
```

…

**Describe the solution you'd like**
>What would the feature look like? How would it work? How would it change the API?

…

**Describe alternatives you've considered**
> Are there alternatives you've tried, and/or workarounds in-place?

Currently investigating use of https://github.com/lestrrat-go/jsschema
…

**Comment by elithrar** [comment]
Have you looked at the referenced https://github.com/lestrrat-go/jsval - ?

**Comment by shivarammysore** [comment]
Yes - It can covert JSON Schema to Go and then, I have not been able to do
much further.  I have used Gorilla toolkit in my code and ran into some
namespace issues too - which can be overcome ... but, code will be hard to
maintain and for someone else to pick up the code, it will be even harder.
Also, I am not sure how many use lestrrat-go packages - hence nervous about
bugs and roadblocks.
