### ISSUE TITLE
[bug] Schema tag doesn't work

### ISSUE THREAD

**Issue by hanrok** [gorilla/schema#128]
**Describe the bug**
Cannot use schema tag, Decode function crashes with MultipleError

**Versions**
> Go version: go version go1.12.7 linux/amd64
> package version: github.com/gorilla/schema@v1.1.0
(Running with Go modules, how can I retrieve git log?)

**Steps to Reproduce**
- Create struct with schema tag
- Try to decode it with NewDecoder
- See that it's not working

```
var request struct {
	OrganizationID int64 `schema:"organization_id"`
	ProjectID      int64 `schema:"project_id"`
}

decoder := schema.NewDecoder()
err := decoder.Decode(&request, r.URL.Query())
if err != nil {
	panic("invalid input")
}
```

When the user requested url that ends like this:
".../something?organization_id=1&project_id=1"

The schema tag is ignored.
Am I do something wrong?

**Expected behavior**
Decode url params and get the result struct

**Comment by elithrar** [comment]
Call
https://golang.org/pkg/net/http/#Request.ParseForm first.

The code you provided is also not valid - “var request struct” is not valid
Go.

**Comment by hanrok** [comment]
Thanks! It's work now.
BTW, the code snippet is a compiled and valid Go code, this is a way to define an anonymous struct.
