### ISSUE TITLE
[bug] Path with a dot lead to an invalid path

### ISSUE THREAD

**Issue by alexisvisco** [gorilla/schema#135]
Hi, I have an url params that contains a dot and this library detect the path as invalid:

Here a runnable example: 
https://goplay.space/#QP6keFtzLKx

Snippet:
```go
package main

import (
	"fmt"

	"github.com/gorilla/schema"
)

var decoder = schema.NewDecoder()

type Person struct {
	Name  string `schema:"with-dot.q"`
	Phone string `schema:"without-dotq"`
}

func main() {
	params := map[string][]string{}

	params["with-dot.q"] = []string{"hello"}
	params["without-dotq"] = []string{"hello"}

	p := Person{}
	err := decoder.Decode(&p, params)

	fmt.Printf("err %q, name %q, phone %q", err.Error(), p.Name, p.Phone)
}
```

There is any reason why the output of this program is: `err "schema: invalid path \"with-dot.q\"", name "", phone "hello"` ?

**Comment by alexisvisco** [comment]
Pretty sure it was introduced in: this merge request : https://github.com/gorilla/schema/pull/25

**Comment by bbckr** [comment]
experiencing this issue as well with params that include a dot in path. please reopen.

If encode supports params with dot, then so should decode imo.

**Comment by ahume** [comment]
I am also bumping into this as a problem. If this is a valid issue can this be reopened? Happy to work on a PR if so.

**Comment by gobijan** [comment]
This is indeed a valid issue and by default gorilla schema doesn't work with gorilla csrf together cause the default name for the csrf token in gorillas own lib is: gorilla.csrf.Token
So the dots trigger Error: schema: invalid path "gorilla.csrf.Token"

**Comment by adamwoolhether** [comment]
Ya, this is unusable with the gorilla CSRF pacakge.

Combine with the fact that the gorilla CSRF package doesn't properly let you change the context key, there's no work around.
