### ISSUE TITLE
[feature]Can support this feature :  map convert to struct  with struct contain same field (upper field  and lower field) 

### ISSUE THREAD

**Issue by RockOwl** [gorilla/schema#145]
**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is - e.g. "I'm always frustrated when [...]"

### My question background
1.  I am build a  http api  struct for OAuth2`s callback, so this struct need Code and  State field
2. But protobuf(to golang) also contain state field.  like this code:

```golang
type MyStruct struct {
	state         protoimpl.MessageState  
	sizeCache     protoimpl.SizeCache  
	unknownFields protoimpl.UnknownFields  

	Code   string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`  
	State  string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`   
//State  string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty" schema:"state,omitempty"`
//  add tag schema is also no effect
}
```

3. When I process http Get params like this, and convert to MyStruct
```golang
inStr := "code=aaa&state=bbbb&state2=ccc"  
values, _ := url.ParseQuery(inStr)

body := &MyStruct{}
err := schema.NewDecoder().Decode(body, values)  //finally,   body.State == "",   no value set
```

4. Obviously，I want gorilla can auto set "bbbb" to the  Upper-case field (State) than lower field (state)
5. Can support the feature ?

**Describe the solution you'd like**
>What would the feature look like? How would it work? How would it change the API?

…

**Describe alternatives you've considered**
> Are there alternatives you've tried, and/or workarounds in-place?

…

**Comment by elithrar** [comment]
Private fields - fields starting with a lower-case value - aren’t publicly
accessible.

This means that this package, or any package outside of your own, cannot
access those fields. There isn’t a feature to “support”.

Take a look at https://tour.golang.org/basics/3

**Comment by RockOwl** [comment]
In this struct,  there are two field:  state  and State,   one is private field and other is public field
And I want to set the public field (struct.State)  when map to struct

**Comment by elithrar** [comment]
Can you fix your code formatting? (it's really hard to read)

You should use the `schema` struct tags to map field names. It's otherwise unclear what you want - if you have overlapping field names, schema can only see the public field.

**Comment by RockOwl** [comment]
> Can you fix your code formatting? (it's really hard to read)
> 
> You should use the `schema` struct tags to map field names. It's otherwise unclear what you want - if you have overlapping field names, schema can only see the public field.

I am tried the tag `schema ` ,  no effect
