### ISSUE TITLE
Support for shopspring decimal.Decimal and time.Time [feature] 

### ISSUE THREAD

**Issue by mrod502** [gorilla/schema#156]
It'd be very helpful to be able to URL encode/decode Decimal and Time types as these are heavily used in finance APIs

**Comment by elithrar** [comment]
A custom type and decoder can achieve that today: https://godoc.org/github.com/gorilla/schema

This kind of custom code should live in app code instead of library code, given that handling decimal data can be sensitive and non-generic.

**Comment by mrod502** [comment]
Ah yes that makes sense
