### ISSUE TITLE
Decode value of type *string

### ISSUE THREAD

**Issue by aigoya** [gorilla/schema#161]
I'm struggling with schema.decode of type *string from html form.

schema version: v1.2.0
golang version: v1.15.6

**Here is my go code**
```go
type Staff struct {
	ID          string
	Birthday   *string
}
```
**Here is my html form**
```html
<form>
	<input type="text" name="ID" value="ST00001"> 
	<input type="date" name="Birthday" value=""> 
</form>
```

because birthday is not provide, after I bind this I wish to get `<nil>`
but schema provide pointer to blank string instead of `<nil>`

**my question is**
How can I get `<nil>` instead of pointer to the blank string?

**Comment by Dri0m** [comment]
I stumbled upon this too. schema seems to zero nil values in this even if it's configured not to zeroEmpty. Since it's still worth it for me to use the parser, I use a bit of reflection to convert all empty strings in the struct back to nil. Annoying.
