### ISSUE TITLE
[feature] Use json struct tags if wanted

### ISSUE THREAD

**Issue by RealHarshThakur** [gorilla/schema#184]
**Is your feature request related to a problem? Please describe.**

I have an API which already accepts JSON as content type, so all the structs have the json tags in them. To add support for form-encoded, I have to now add `schema` tags to each field same as json tag. 
…

**Describe the solution you'd like**

I was hoping json tags can be picked up as a fallback when schema tags aren't provided. 

…

**Describe alternatives you've considered**
> Are there alternatives you've tried, and/or workarounds in-place?

…

**Comment by logansam** [comment]
You can use the SetAliasTag method on the decoder to change the name of the struct tag 

`
schemaDecoder = schema.NewDecoder()
schemaDecoder.SetAliasTag("json")
`

**Comment by RealHarshThakur** [comment]
Thanks, that sounds amazing.
