### ISSUE TITLE
⚠️ The Gorilla Toolkit is Looking for a New Maintainer

### ISSUE THREAD

**Issue by elithrar** [gorilla/schema#187]
The Gorilla Toolkit is looking for a new maintainer (or maintainers, plural). As the last standing maintainer of the project, I no longer have time to fully dedicate to maintaining the libraries here, and 

The major libraries - **mux** (https://github.com/gorilla/mux), **schema** (https://github.com/gorilla/schema), **handlers** (https://github.com/gorilla/handlers), and **sessions** (https://github.com/gorilla/sessions), are all reasonably mature libraries, but ongoing stewardship around bug triage, feature enhancements, and potential "version 2.0s" are all possibilities.

* Have a demonstrated history of OSS contributions. This is important, as you need to be trustworthy: _no_ maintainer is better than an adversarial maintainer!
* Ideally, you actively contribute for 3-6 months, I merge after you review, and you gain the commit bit on the relevant repos after that period and/or active engagement on your part.
* I transition you to admin of the project.

> Note: I don't expect this to be quick or easy - the **websocket** library, with 16k stars & 15k unique clones per week, has been [looking for a new maintainer](https://github.com/gorilla/websocket/issues/370) 3.5+ years, and has yet to have anyone reliably stick. If I don't have any luck finding new maintainer(s) in the next 6 months or so, it's likely I'll mark these projects as in maintenance mode only and [archive](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories) the repos.

Please keep the replies on-topic.

_Cross-posted from https://github.com/gorilla/mux/issues/659_

**Comment by zak905** [comment]
Hi @elithrar, do you have some spare time to take a look at #183 ? It could be a good starting point to define whether I am a good fit to become a maintainer for the schema  project

**Comment by elithrar** [comment]
@zak905 it would make more sense for others to properly code review - I just don't have the time to look at medium/large PRs.

**Comment by zak905** [comment]
Ok. who do you mean by others ? the community ? or other maintainers

**Comment by elithrar** [comment]
@zak905 Others in the community - for example, some of the folks that indicated interest in this thread!

Note: There aren't "other" maintainers right now, and don't @ a bunch of folks to review/merge your PR. Please be patient: there's nothing stopping you from using your fork in the meantime.

**Comment by zak905** [comment]
Ok thanks.

 I am also not a fan of @ at people, and this was a last resort solution because the bot put a stale mark today, and after almost 6 months I thought I had to do something. I am not expecting it to get merged, but at least some feedback and discussion.  Looks like things are quiet dead at Gorilla.

**Comment by zak905** [comment]
Hi @elithrar, I see the repo was idle for a while, and I am just wondering if anybody has been assigned as a repo maintainer. I thought it was @DavidLarsKetch, but his seems to be off the grid for a while now.

**Comment by elithrar** [comment]
No one has consistently stepped up for any of the Gorilla projects so far.

**Comment by zak905** [comment]
it would a pity to see the repos go into maintenance mode. I did not find anyone to help with PR review process ( it seems like there is an interest for this functionality)

**Comment by zak905** [comment]
Hi @elithrar, we are trying hard to keep the repo alive, but we are not seeing much enthusiasm from your side. It would help if you could share with us your up-to-date plans

Since it's hard to find maintainers for each single project, I think a cool alternative in this case would be giving away the whole organization to some organization/company that takes care of OS projects properly (like RedHat or Google for example). I don't know how it works but it's just a thought that crossed my mind

**Comment by gudvinr** [comment]
There is https://gof.rs/ but ironically [their fork](https://github.com/gofrs/websocket) of gorilla/websockets is outdated even compared to original repo

**Comment by elithrar** [comment]
We've decided to archive the Gorilla project, including this one. You can read more here: https://github.com/gorilla/mux/issues/659#issuecomment-1344468929
