### ISSUE TITLE
Not checking for nil might lead to nil pointer dereference 

### ISSUE THREAD

**Issue by rzajac** [gorilla/schema#190]
https://github.com/gorilla/schema/blob/8285576f31afd6804df356a38883f4fa05014373/encoder.go#L167-L173

The `f` should be checked for `nil` before it is used in closure.

**Comment by zak905** [comment]
Hi @rzajac, do you have an example that triggers a panic ? I think that if `f` is `nil` than `v` will be `nil` as well, and therefore the closure will return always "null" value, so `f(v.Elem()) ` statement will not be reached 

I tried to trigger the case you mentionned but I was not able to 

```
func TestNilPointerDeference(t *testing.T) {
	type C struct {
		R int `schema:"R"`
	}

	type B struct {
		C *C `schema:"C"`
	}

	b := B{C: (*C)(nil)}

	encoder := NewEncoder()

	vals := url.Values{}

	if err := encoder.Encode(b, vals); err != nil {
		t.Fatalf(err.Error())
	}
}
```

The test is passing without errors.

**Comment by zak905** [comment]
@elithrar this can be closed I think

**Comment by jaitaiwan** [comment]
Thanks heaps @zak905 closing

**Comment by zak905** [comment]
sure thing!
