### ISSUE TITLE
[FEATURE] Documentation

### ISSUE THREAD

**Issue by bconn98** [gorilla/schema#208]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem? Please describe.

No where in the README (the only documentation I can find), does it say that the fields of the structs need to be public. That's a basic and easy concept to add to the documentation.

### Describe the solution that you would like.

Documentation on using the tools

**Comment by AlexVulaj** [comment]
Hey @bconn98 , thanks for bringing this up - it's a good suggestion. Would you mind opening up a pull request with what you had in mind and linking it to this issue?

**Comment by bconn98** [comment]
It'll take me a bit to get to, but will do.

**Comment by jaitaiwan** [comment]
I think that it is implicit in how Go works. I understand that for folks new to Go it might not be obvious — but there's no way for an ext library (except maybe reflect but haven't looked into that) to see the private fields of a struct. I'm okay with it being documented, I don't think it can hurt... Just noting I don't think it's strictly necessary.

**Comment by jaitaiwan** [comment]
From what I can tell, there's a bug complaining about unexported fields actually being exported anyway (#203) so I'm going to close this one out and note that we'll document the difference when we do a fix for the aforementioned bug.
