### ISSUE TITLE
Preferred way for multiple checkboxes

### ISSUE THREAD

**Issue by viru** [gorilla/schema#22]
Question about best practice when dealing with form that:

* Has multiple checkboxes as an answers to one question, eg. Shop Type: [] electronics, [] groceries, [] wines, [] something

* Answer options (checkbox values and ids) are fetched from DB

I thought that the best option would be to go with nested struct:

```go
type shopType struct {
    Id int
    Type string
    Selected bool
}

type shopForm struct {
    Name string
    Types []shopType
}
```

Then populating shopForm.Types from DB and using it as a context in template. Then in template:

```html
{{ range $idx, $type := .Types }}
    <label class="checkbox-inline"><input type="checkbox" name="Types.{{ $idx }}.Selected" {{ if $type.Selected }}checked{{ end }}> {{ $type.Type }}</label>
{{ end }}
```

But the problem with this approach is that I can only decode Selected field and I'm missing Id and Type. I could add hidden input fields like this:

```html
<input type="hidden" name="Types.{{ $idx }}.Id" value="{{ $type.Id }}">
<input type="hidden" name="Types.{{ $idx }}.Type" value="{{ $type.Type }}">
```

and then it works OK, but it's ugly and it can't be done when dealing with select option form.

I'm probably missing something obvious :)

**Comment by elithrar** [comment]
Going to close this one due to inactivity / since it's a question, but feel free to open a new issue if problems persist ;)
