### ISSUE TITLE
Question May I open an PR to refactor or organize the test code in decoder_test.go?

### ISSUE THREAD

**Issue by lll-lll-lll-lll** [gorilla/schema#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Anything else?

May I open an PR to refactor or organize the test code in decoder_test.go?

Why

There is test code from over 10 years ago, and when adding new tests, I find it difficult to check whether similar test code has already been written.

I think this is somewhat unavoidable, but if there are tests that can be consolidated, perhaps we could do so. What do you all think?

**Comment by jaitaiwan** [comment]
Go for it!
