### ISSUE TITLE
[BUG] User specified value 0 is ignored when default is not zero

### ISSUE THREAD

**Issue by klajok** [gorilla/schema#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Following code prints the default integer value `10` of field `Level`, despite the fact that specified `level` was `"0"`.
```go
type Example struct {
	Level int `schema:"level,default:10"`
}

func main() {
	var example Example
	input := map[string][]string{"level": {"0"}}

	schema.NewDecoder().Decode(&example, input)

	// instead of 0 program prints 10
	fmt.Println(example.Level)
}
```

### Expected Behavior

Decoder should not ignore user specified integer value even if it is equal to 0. Program should print `0`.

### Steps To Reproduce

Run the above program.

### Anything else?

This bug affects fields of type `int`, `uint32`, `float64`,... and so on.

**Comment by jaitaiwan** [comment]
Mismatched types. Should be `map[string]string{}` not `map[string][]string{}`

**Comment by klajok** [comment]
I think the type shown in the example snippet is correct. It matches the type `url.Values`. Additionally the proposed type `map[string]string` causes compilation error.

But... today I have finally spotted big blue note at the very bottom of README:
> Because primitive types like int, float, bool, unint and their variants have their default (or zero) values set by Golang, it is not possible to distinguish them from a provided value when decoding/encoding form values. In this case, the value provided by the `default` option tag will be always applied. (...) In such cases, it is highly recommended to use pointers to allow schema to distinguish between when a form field has no provided value and when a form has a value equal to the corresponding default set by Golang for a particular type.

I'm not sure about encoding, but in case decoding we have all values in the form of map of string list. We can easily distinguish between `[""]`, `["0"]` and no entry in the values map.

As a workaround we use following code (adapted to the reported "example") - it works but looks ugly:
```go
value := input["level"] 
// inspect **last** value of the potentially polluted HTTP param (to be consistent
// with behavior of other library which parses HTTP parameters)
if len(value) > 0 && value[len(value)-1] == "0" {
  example.Level = 0
}
```
This proves that it is possible to "distinguish them [default (or zero) values] from a provided value".
