### ISSUE TITLE
Decode to maps

### ISSUE THREAD

**Issue by chrneumann** [gorilla/schema#24]
If you know your fields (and their types) only at runtime, there is no way to decode values to them. Structs have to be defined at compile time.

A possible solution would be to support maps as target values. For example:

``` go
values := map[string][]string{
    "Name":  {"John"},
    "Age": {"55"},
}
person := make(map[string]interface{})
person["Name"] = new(string)
person["Age"] = new(int)
decoder := schema.NewDecoder()
decoder.Decode(person, values)
```

There could also be support for nested maps, but I guess it would be ok to just support flat maps with fields like "nested.key".

Other ideas?

**Comment by kisielk** [comment]
I agree this would be a good feature. Unfortunately I don't have time to work on this at the moment, marking as HelpWanted.

**Comment by FX-HAO** [comment]
Any progress?

**Comment by zhangguanzhang** [comment]
> Any progress?

have you to resolve this ?
