### ISSUE TITLE
Panic on invalid data provided by the client

### ISSUE THREAD

**Issue by fln** [gorilla/schema#33]
Decode() method panics if source data contain invalid fields having path parts with names of other fields. 

Its better to illustrate this with example. This code will panic on execution:
```go
package main

import "fmt"
import "github.com/gorilla/schema"

func main() {
        type Person struct {
                Person string `schema:"person"`
                Phone  string `schema:"phone"`
        }

        values := map[string][]string{
                "person.phone":  {"John"},
                "phone":  {"999-999-999"},
        }
        person := new(Person)
        decoder := schema.NewDecoder()
        decoder.Decode(person, values)
        fmt.Println(person)
}
```

The panic occurs only if source data have names of other variables. For example changing `values` to:
```go
        values := map[string][]string{
                "person.phones":  {"John"},
                "phone":  {"999-999-999"},
        }
```
is handled correctly (`phone` part of the path is changed to `phones` which does not collide with other attribute name).

Values is usually in control of the client of the application. This bug allows client to cause panic on the server by manipulating GET or POST arguments.

**Comment by elithrar** [comment]
Addressed in https://github.com/gorilla/schema/pull/35
