### ISSUE TITLE
RegisterConverter for custom type not behaving as expected

### ISSUE THREAD

**Issue by zhchang** [gorilla/schema#37]
https://github.com/gorilla/schema/commit/6e77d1705e72ae1e3c440177c2c2c6fd9179019a#diff-e03ef7ae325cb767cea50982da58c5cdR58

type Custom1 string
and
type Custom2 string

are of same Kind(), but can use totally different converter, I think this recent change will led to overwriting of converters registered of totally different types.

**Comment by kisielk** [comment]
Hm I think you're right. @spirozh do you have any ideas for a fix for this?

**Comment by kisielk** [comment]
Reverted the commit for now until the issue can be fixed.

**Comment by spirozh** [comment]
the first solution that comes to mind is to:
1) add a unit test for decoder.RegisterConverter
2) store the registered converters in their own map keyed on type, if there
isn't one registered then fall back to type based converters.

**Comment by kisielk** [comment]
Yeah, that's about the same conclusion I came to as well, using a separate map for custom converters.

Really we should also add support for the Text(Un)Marshaler interface and encourage people to stop registering the custom converters.

**Comment by kisielk** [comment]
Should be fixed now, also tested :+1:
