### ISSUE TITLE
Handle empty values appropriately

### ISSUE THREAD

**Issue by cwc** [gorilla/schema#4]
In the decoder, [lines 110-112](https://github.com/gorilla/schema/blob/master/decoder.go#L110-L112) cause a panic in the handling of slices, due to the [items array](https://github.com/gorilla/schema/blob/master/decoder.go#L99) having already been created according to the length of `values`. Skipping the handling of a value causes the corresponding index in `items` to contain invalid/zero Value objects.

Adding insult to injury, this even occurs when parsing a slice of strings (e.g. `{ "0", "1", "" } => []string => panic!`).

**Comment by elithrar** [comment]
Addressed in https://github.com/gorilla/schema/pull/9
