### ISSUE TITLE
Converting comman seperated strings into slice of string.

### ISSUE THREAD

**Issue by henrikbjorn** [gorilla/schema#40]
Currently if I add a custom converter like `decoder.RegisterConverter([]string{}, func (input string) reflect.Value {})` it wont call the custom converter but instead ignore it.

``` go
package schema_test

import (
	"fmt"
	"reflect"
	"testing"

	"github.com/gorilla/schema"
)

func TestStrings(t *testing.T) {
	decoder := schema.NewDecoder()
	decoder.RegisterConverter([]string{}, func(input string) reflect.Value {
		fmt.Printf("%+v", input)

		return reflect.ValueOf(input)
	})

	i := struct {
		Multiple []string `schema:"multiple"`
	}{}

	decoder.Decode(&i, map[string][]string{
		"multiple": []string{"one,two,three"},
	})
}
```

Would have suspected `i.Multiple` to contain a `[]string{"one", "two", "three"}`

**Comment by kisielk** [comment]
The above fix should work.

**Comment by Demznak** [comment]
hello, I have problem when I convert slice 
decoder.RegisterConverter([]string{}, func (input []string) reflect.Value {})

func(input []string) reflect.Value {
       for _, val := range input {
              fmt.P rintf("%+v", val)
              //validate val   
              //if err  {return reflect.Value{}}
       }
        return reflect.ValueOf(input)
    }
