### ISSUE TITLE
gopkg versioned packages

### ISSUE THREAD

**Issue by henrikbjorn** [gorilla/schema#41]
We vendor in our dependencies currently, but personally my gospace is still shared across different packages (as a project is just a package anyways). Because of that i think it would be a good idea to use gopkg.in and tag the packages.

What do you think about that?

**Comment by kisielk** [comment]
I've though about it in the past, but I think that that ultimately something like gb will be a better solution that will make it unnecessary.

**Comment by henrikbjorn** [comment]
Maybe i am not understanding gb right. But it doesnt seem to solve the versioning problem.

**Comment by kisielk** [comment]
It does solve the problem in the sense that if you have a project with schema, you can lock it to a particular revision. Each project you work on could be locked to a different version, if that's what you want.

**Comment by henrikbjorn** [comment]
Thats why i like gopkg.in because you just tag a version and i decide if i want to lock down a major, minor or patch version. Also it doesnt really require that much maintenance as it is completely automatic.

Just `git tag` a version using the semver scheme and you support the best of both (people who want to use gb and people who just want go install and simple gopkg.in)

**Comment by kisielk** [comment]
Well, semantic versioning is automatic for the user of the package, but it does add more overhead to maintaining the package itself. I have pretty limited time to maintain these projects and remembering to deal with tagging for every one of them is not an insignificant overhead. One of the things I like about the Go ecosystem is that it's not normally an issue, and with gb or even godep you can still lock down to a particular revision of a package without the package's author having to worry about it.

**Comment by elithrar** [comment]
I'm going to close this as:

* Go 1.5 includes preliminary support for vendoring via `GOVENDOREXPERIMENT=1` and vendoring dependencies into `/vendor`.
* Tools like [godep](https://github.com/tools/godep) and [gb](https://github.com/constabulary/gb) assist with this
* The Gorilla packages take API stability very seriously, so the reality is that any gopkg.in URL wouldn't be any different from using the GitHub import URL.

Happy to re-open if there's other arguments to bring to the table but I think the vendoring path is the way to go here.
