### ISSUE TITLE
README.md would be nice

### ISSUE THREAD

**Issue by dborzov** [gorilla/schema#42]
Found this as a dependency in slackbot and have no clue what that is

**Comment by elithrar** [comment]
All of the Gorilla repos have full docs here:
http://www.gorillatoolkit.org/pkg/schema (but you're right, the README
should either inherit that content, or at least link to it).

**Comment by elithrar** [comment]
Got some copypasta going over my morning coffee - the PR should make the README a little friendlier :ok_hand:
