### ISSUE TITLE
Struct to values "encoder"

### ISSUE THREAD

**Issue by kladd** [gorilla/schema#44]
I've been using schema for a while, but I'd also like the ability to encode url values with the fields of a struct. I've created a basic encoder [here](https://github.com/kladd/urlvalues), do you have any interest in adding something like this to schema?

**Comment by JohnMaguire** [comment]
@kisielk Are you interested in a pull request for this feature?

**Comment by kisielk** [comment]
Yes, hence the HelpWanted tag. I was hoping @kladd might adapt his repo for the purpose to avoid duplicating any work...

**Comment by JohnMaguire** [comment]
@kisielk Sounds like he's willing, maybe he just didn't see the tag added since he wasn't mentioned?

**Comment by kisielk** [comment]
That's a good point. I thought I commented on it at the time but I guess I forgot. I was triaging dozens of issues / PRs so ... :) Hopefully he will see it now!

**Comment by kladd** [comment]
Hi all, I do see now. I'll get a PR going in a bit.
