### ISSUE TITLE
Proposal: Add Type to ConversionError

### ISSUE THREAD

**Issue by ilgooz** [gorilla/schema#48]
I'd like to response graceful error messages to user for given type of invalid field. See new version of ConversionError below. I'd like to implement this. Refer to link for more information: https://github.com/ajg/form/issues/5

e.g.
```go
type ConversionError struct {
    Key   string
    Type reflect.Type
    Index int    
    Err   error  
}
```

**Comment by kisielk** [comment]
So basically you're proposing adding the Type field? The others are already there.

**Comment by ilgooz** [comment]
Yep

**Comment by kisielk** [comment]
Would it really be that much more helpful? You already get the key name so can just look up the struct definition.

**Comment by ilgooz** [comment]
I guess I can get the field type that way by using reflection but it's just extra work and I also need to manage some caching for those types to improve performance. But it's all OK. Feel free to close the issue.

**Comment by kisielk** [comment]
I guess my question is about the usefulness of having the type name in the error message. For the programmer it seems it would be enough to have the field name. Or do you have some other purpose in mind, where your program would inspect the type?

**Comment by ilgooz** [comment]
Yes, I've a wrapper func that parses the form to given struct and does some validation afterwards. Finally it returns an err next to the list of invalid fields. Since I use a wrapper func to avoid extra work on each http handler, I wouldn't manually check the struct to see the type of invalid fields and therefore I can't produce a specific error message for that type.

e.g.:
```go
type User struct {
  Age int `schema:"age" validate:"max:30"`
  Time time.Time `schema:"time"`
}

var user User

invalids, err := parseForm(r.Form, &user)
if err != nil {
  w.WriteHeader(http.IntervalServerError)
  return
}

// some possible values of `invalids` 

// if all valid
map[string]string{}
// if age field is not an int
map[string]string{
  "age": "must be a number", // parsing err
}
// if age over 30 and time is not valid
map[string]string{
  "age": "must be greater than 30", // validation error
  "time": "time must be UTC formatted", // parsing err
}

// then I can simply response a json error message to user:
errRes := struct {
  Message string
  Fields map[string]string
}{"Unvalid form data", invalids}
json(w, http.StatusBadRequest, errRes)
```

**Comment by kisielk** [comment]
right, but you wouldn't just return the type string to the user since it could be any arbitrary go type? It seems to me it wouldn't have much meaning to a client of a web service

**Comment by ilgooz** [comment]
of course, I never return the go type as a json error response. I produce pretty error messages depending on those types in my API and send them as a response. For example if I expect a field as a UTC time and it can not being parsed to time.Time I simply say "this field is not a valid time" or a field's value expected as a bool but given value doesn't satisfy strconv.ParseBool() then I say "this field is not bool"

**Comment by ilgooz** [comment]
by the way the *Type* that I talking about in *ConversionError* is the expected type of the field

**Comment by kisielk** [comment]
Right. I guess one complication is what to return in the cases of slice elements and how to differentiate between the error being a slice not passed as the value, or one of the elements being the wrong type..
