### ISSUE TITLE
Sanitization

### ISSUE THREAD

**Issue by genexp** [gorilla/schema#71]
Hi All - I have a use case where I have little control over the incoming JSON.  I'd like to do some sanitization on the object keys (all keys, on all nested objects) before I map it to a struct.  Specifically, I'd like ensure that all keys have the same case (In my case, camelCase)  Is there some way to scrub the JSON object before decoding it?

**Comment by kisielk** [comment]
You're free to edit the map being passed to the decoder as much as want beforehand. Or is there something else keeping you from doing that?

**Comment by genexp** [comment]
I think that would work. Frankly, I'm just not totally clear what that looks like. I'll spend more time with the documentation.
