### ISSUE TITLE
Encode method is returning inaccurate errors

### ISSUE THREAD

**Issue by carlqt** [gorilla/schema#75]
I have this snippet here, the problem is that the `error` returned by the `Encode` method gives `(0 errors)`, this is what `err` displays when I print in int stdout. I'm not sure if an error occurred or should I treat this as a no error and move on with the code...
```
func (t *Ticket) Create() {
	encoder := schema.NewEncoder()

	// setup form values
	form := url.Values{}
	err := encoder.Encode(t, form)
	if err != nil {
		panic(err)
	}
}

```

**Comment by elithrar** [comment]
Why should it return an error?

**Comment by carlqt** [comment]
I mean, the if condition is evaluated as true because that's the value of 'err' after the encode. So the err value is not nil BUT when I print the value of err to see what happened, the err value display (0 errors).

**Comment by olliephillips** [comment]
Hello, I encountered this today. 

Looking for ```err != nil``` as normal. Was scratching my head for a bit.
Would be good to standardise this return.

The code example in the README - see my annotation in the comments

```
var encoder = schema.NewEncoder()

func MyHttpRequest() {
    person := Person{"Jane Doe", "555-5555"}
    form := url.Values{}

    err := encoder.Encode(person, form)

    if err != nil {
        // Handle error
  -->// (0 errors) != nil, but there was no error
    }

    // Use form values, for example, with an http client
    client := new(http.Client)
    res, err := client.PostForm("http://my-api.test", form)
}
```
