### ISSUE TITLE
Have to consult a Form value before decode into object

### ISSUE THREAD

**Issue by sredXNY** [gorilla/schema#83]
Hi, I'm using gorilla/schema to populate my structure, righ now I'm getting a strange behaviour when I Decode the form into my struct. I am developing a CRUD for the table _users_ and right now I am making the Update part.. So, briefly I get an ID, search in db for that register and finally I decode the form into the existent user in order to override the new fields to update, but now, I am testing with the field _name_ and it's not assigned unless I retrieve that value before using _req.FormValue_ . I have something like:
```

type User struct {
	gorm.Model
	Name string
       Active bool
}
```

Then in the code to set the values:

```
user := models.User{}
decoder := schema.NewDecoder()
err := decoder.Decode(&user, req.PostForm)
```

But that doesn't work, intead of that I have to retrieve some value from the form and then the decode is made successfully, something like:

```
user := models.User{}
fmt.Println(req.FormValue("Name"))
decoder := schema.NewDecoder()
err := decoder.Decode(&user, req.PostForm)
```

And here that works pretty well, I have to consult the value I don't know why.

**Comment by corburn** [comment]
You need to call [Request.ParseForm](https://golang.org/pkg/net/http/#Request.ParseForm) first. 

[Request](https://golang.org/pkg/net/http/#Request)
```go
// PostForm contains the parsed form data from POST, PATCH,
// or PUT body parameters.
//
// This field is only available after ParseForm is called.
// The HTTP client ignores PostForm and uses Body instead.
PostForm url.Values
```

[Request.FormValue](https://golang.org/pkg/net/http/#Request.FormValue)
> FormValue returns the first value for the named component of the query. POST and PUT body parameters take precedence over URL query string values. **FormValue calls ParseMultipartForm and ParseForm if necessary** and ignores any errors returned by these functions. If key is not present, FormValue returns the empty string. To access multiple values of the same key, call ParseForm and then inspect Request.Form directly.

**Comment by sredXNY** [comment]
@corburn ohh I see!! Thank you man!
